### ISSUE TITLE
Coala next - roadmap to coala v0.0.3

### ISSUE THREAD

**Issue by cheft** [Qfang-FrontEnd/coala#2]
- [x]  增加 [__this.$__], 指向 this.el.find ，更方便查找 DOM 元素
- [ ]  简化复杂的上下级组件查询 api
- [x] 丢弃 refs 的 API 简化模式
- [x] 增加 coala.component API 实例化 Component 对象
- [x] 增加 coala.unmount API 卸载 Component 对象
- [x] demo中 加入 css 模块加载器
- [x] fix #4

**Comment by cheft** [comment]
- [x]  增加 [__this.$__], 指向 this.el.find ，更方便查找 DOM 元素
- [ ]  简化复杂的上下级组件查询 api
- [x] 丢弃 refs 的 API 简化模式
- [x] 增加 coala.component API 实例化 Component 对象
- [x] 增加 coala.unmount API 卸载 Component 对象
- [x] demo中 加入 css 模块加载器
- [ ] fix #4

**Comment by cheft** [comment]
release v0.0.3.

- [ ]  简化复杂的上下级组件查询 api

考虑到性能与版本兼容性问题，这个版本先不加
